"""add body html field on post

Revision ID: 3a949748e1ae
Revises: 5a614791e7be
Create Date: 2022-10-19 23:55:20.423864

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a949748e1ae'
down_revision = '5a614791e7be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'categories', ['id'])
    op.add_column('posts', sa.Column('body_html', sa.Text(), nullable=True))
    op.alter_column('posts', 'category_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('posts', 'category_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('posts', 'body_html')
    op.drop_constraint(None, 'categories', type_='unique')
    # ### end Alembic commands ###
