"""add image field

Revision ID: 966de7e1f259
Revises: 4b49ef6e22dd
Create Date: 2022-10-09 15:12:30.308613

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '966de7e1f259'
down_revision = '4b49ef6e22dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('image', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'tags', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tags', type_='unique')
    op.drop_column('posts', 'image')
    # ### end Alembic commands ###
